import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  schedulelSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Home',
      className: 'scheduleItem scheduleItem--home',
    },
    
    {
      type: 'category',
      label: 'Turma',
      className: 'scheduleItem scheduleItem--turma',
      items: [
        {
          type: 'autogenerated',
          dirName: 'turma',
        },
      ],
    },
    {
      type: 'category',
      label: 'Professor',
      className: 'scheduleItem scheduleItem--professor',
      items: [
        {
          type: 'autogenerated',
          dirName: 'professor',
        },
      ],
    },
    {
      type: 'category',
      label: 'Sala',
      className: 'scheduleItem scheduleItem--sala',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sala',
        },
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebarSectionTitle">INFORMAÇÕES DO CAMPUS</div>',
      defaultStyle: true,
      className: 'campusInfoGroupTitle',
    },
    {
      type: 'doc',
      id: 'campus/administracao',
      label: 'Administração',
      className: 'campusInfoItem campusInfoItem--administracao',
    },
    {
      type: 'category',
      label: 'Cursos',
      collapsible: true,
      collapsed: true,
      className: 'campusInfoItem campusInfoItem--cursos',
      items: [
        {
          type: 'html',
          value: '<div class="sidebarSectionHeading">TÉCNICOS</div>',
          defaultStyle: true,
        },
        'cursos/tecnico-administracao-integrado',
        'cursos/tecnico-eventos-integrado',
        'cursos/tecnico-informatica-integrado',
        'cursos/tecnico-administracao-subsequente',
        'cursos/tecnico-gastronomia-subsequente',
        'cursos/tecnico-guia-de-turismo-subsequente',
        {
          type: 'html',
          value: '<div class="sidebarSectionHeading">LICENCIATURA</div>',
          defaultStyle: true,
        },
        'cursos/licenciatura-fisica',
        'cursos/licenciatura-matematica',
        {
          type: 'html',
          value: '<div class="sidebarSectionHeading">TECNOLOGIA</div>',
          defaultStyle: true,
        },
        'cursos/tecnologia-gastronomia',
        'cursos/tecnologia-sistemas-para-internet',
      ],
    },
    {
      type: 'category',
      label: 'Contato',
      collapsible: true,
      collapsed: true,
      className: 'campusInfoItem campusInfoItem--contato',
      items: [
        {
          type: 'html',
          value:
            '<div class="campusInfoSubItem campusInfoSubItem--telefone"><span class="campusInfoSubItem__label">Telefone</span><span class="campusInfoSubItem__value">(89) 2221-9904</span></div>',
          defaultStyle: true,
        },
        {
          type: 'html',
          value:
            '<div class="campusInfoSubItem campusInfoSubItem--endereco"><span class="campusInfoSubItem__label">Endereço</span><span class="campusInfoSubItem__value">BR 020, S/N, Bairro Primavera, São Raimundo Nonato - PI, CEP 64770-000</span></div>',
          defaultStyle: true,
        },
      ],
    },
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],
  
};

export default sidebars;
